'use client';

import { FormEvent, useEffect, useState } from 'react';
import { API_BASE, fetchWithTimeout, readApiError } from '../../lib/api';
import styles from './dashboard.module.css';

type Summary={activePaidSubscriptions:number;activeFreeSubscriptions:number;activeManualGrants:number;expiringWithin30Days:number;monthlyRecurringRevenueFjd:number};
type Plan={code:string;name:string;audience:string;monthlyPriceFjd?:number|null;isPaid:boolean;activeMembers:number;manualGrants:number};
type Demand={planCode:string;count:number};
type Account={userId:string;email:string;displayName?:string|null;accountStatus:string;identityVerified:boolean;requestedPlanCode:string;planCode:string;planName:string;subscriptionStatus:string;billingProvider?:string|null;billingInterval?:string|null;currentPeriodEnd?:string|null};
type Payload={summary:Summary;plans:Plan[];requestedPlans:Demand[];accounts:{items:Account[];page:number;pageSize:number;total:number}};

export default function AdminMembershipsPanel(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[query,setQuery]=useState(''),[status,setStatus]=useState(''),[planCode,setPlanCode]=useState(''),[page,setPage]=useState(1);
 const[grantUser,setGrantUser]=useState<Account|null>(null),[grantPlan,setGrantPlan]=useState(''),[expiresAt,setExpiresAt]=useState(dateAfter(30)),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void load(1,'','','')},[]);

 async function call(path:string,init:RequestInit={}){
  const token=sessionStorage.getItem('fijilaw_access_token')??'';
  const response=await fetchWithTimeout(`${API_BASE}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},cache:'no-store'},15000);
  if(response.status===401){sessionStorage.removeItem('fijilaw_access_token');window.location.href='/account?mode=login';throw new Error('Your session expired.')}
  if(response.status===403)throw new Error('Active, verified System Administrator access is required.');
  if(!response.ok)throw new Error(await readApiError(response,'The membership request could not be completed.'));
  return response;
 }
 async function load(nextPage=page,nextQuery=query,nextStatus=status,nextPlan=planCode){
  setLoading(true);setError('');
  try{const params=new URLSearchParams({page:String(nextPage),pageSize:'50'});if(nextQuery.trim())params.set('q',nextQuery.trim());if(nextStatus)params.set('status',nextStatus);if(nextPlan)params.set('planCode',nextPlan);const response=await call(`/api/admin/memberships?${params}`);const body:Payload=await response.json();setData(body);setPage(body.accounts.page)}
  catch(e){setError(e instanceof Error?e.message:'Memberships could not be loaded.')}finally{setLoading(false)}
 }
 async function search(event:FormEvent){event.preventDefault();setPage(1);await load(1,query,status,planCode)}
 function changeStatus(value:string){setStatus(value);setPage(1);void load(1,query,value,planCode)}
 function changePlan(value:string){setPlanCode(value);setPage(1);void load(1,query,status,value)}
 function clearFilters(){setQuery('');setStatus('');setPlanCode('');setPage(1);void load(1,'','','')}
 function openGrant(account:Account){setGrantUser(account);setGrantPlan(data?.plans.find(isIndividualPaidPlan)?.code??'');setExpiresAt(dateAfter(30));setReason('');setError('');setNotice('')}
 async function grant(event:FormEvent){event.preventDefault();if(!grantUser)return;setBusy(true);setError('');try{await call(`/api/admin/memberships/users/${grantUser.userId}/grant`,{method:'PUT',body:JSON.stringify({planCode:grantPlan,expiresAt:new Date(`${expiresAt}T23:59:59`).toISOString(),reason})});setNotice(`Manual access granted to ${grantUser.email}.`);setGrantUser(null);await load()}catch(e){setError(e instanceof Error?e.message:'Manual access could not be granted.')}finally{setBusy(false)}}
 async function revoke(account:Account){const supplied=window.prompt(`Reason for revoking the administrator grant for ${account.email}:`,'Administrator access review');if(supplied===null)return;if(supplied.trim().length<8){setError('A reason of at least 8 characters is required.');return}if(!window.confirm(`Revoke the manual ${account.planName} grant? Provider payments will not be changed.`))return;setBusy(true);setError('');try{await call(`/api/admin/memberships/users/${account.userId}/grant/revoke`,{method:'POST',body:JSON.stringify({reason:supplied})});setNotice(`Manual access revoked for ${account.email}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Manual access could not be revoked.')}finally{setBusy(false)}}
 const maxDemand=Math.max(1,...(data?.requestedPlans.map(item=>item.count)??[1])),totalPages=Math.max(1,Math.ceil((data?.accounts.total??0)/50));

 return <div className={styles.stack} style={{gap:16}}>
  <section className={styles.hero} style={{marginBottom:0}}><div><p className={styles.eyebrow} style={{color:'#F4D28A'}}>COMMERCIAL ACCESS CONTROL</p><h2>Membership operations</h2><p>Monitor plan access, subscription periods and time-bounded administrator grants without rewriting payment-provider records.</p></div><span className={styles.heroTag}>FJD {data?.summary.monthlyRecurringRevenueFjd.toLocaleString(undefined,{maximumFractionDigits:2})??'—'} MRR</span></section>
  {error&&<p role="alert" style={errorBox}>{error}</p>}{notice&&<p role="status" style={noticeBox}>{notice}</p>}
  <div style={summaryGrid}><SummaryCard label="Active paid" value={data?.summary.activePaidSubscriptions} note="Current paid subscriptions"/><SummaryCard label="Active free" value={data?.summary.activeFreeSubscriptions} note="Current free subscriptions"/><SummaryCard label="Manual grants" value={data?.summary.activeManualGrants} note="Administrator-issued access"/><SummaryCard label="Expiring soon" value={data?.summary.expiringWithin30Days} note="Ends within 30 days"/><SummaryCard label="MRR" value={data?'FJD '+data.summary.monthlyRecurringRevenueFjd.toLocaleString(undefined,{maximumFractionDigits:2}):undefined} note="Excludes manual grants"/></div>
  <section className={styles.card}><div style={heading}><div><p className={styles.eyebrow}>PLAN PORTFOLIO</p><h3 style={title}>Membership plans</h3></div><a href="/pricing" style={pricingLink}>View public pricing</a></div><div style={planGrid}>{data?.plans.map(plan=><article key={plan.code} style={{...planCard,borderTopColor:plan.isPaid?'#E5A93C':'#8CA2B3'}}><span style={audience}>{plan.audience.replaceAll('_',' ')}</span><h3 style={{margin:'9px 0 5px'}}>{plan.name}</h3><strong style={price}>{plan.monthlyPriceFjd==null?'Custom':plan.monthlyPriceFjd===0?'Free':`FJD ${plan.monthlyPriceFjd}/mo`}</strong><div style={planStats}><span>{plan.activeMembers} active</span><span>{plan.manualGrants} manual</span></div></article>)}</div></section>
  <div className={styles.grid}><section className={styles.card}><p className={styles.eyebrow}>REGISTRATION INTENT</p><h3 style={title}>Requested plans</h3><div style={{display:'grid',gap:11,marginTop:18}}>{data?.requestedPlans.map(item=><div key={item.planCode} style={demandRow}><span>{nameFor(item.planCode,data?.plans)}</span><div style={track}><div style={{...fill,width:`${Math.max(4,(item.count/maxDemand)*100)}%`}}/></div><strong>{item.count}</strong></div>)}</div></section><section className={styles.card}><p className={styles.eyebrow}>CONTROL BOUNDARY</p><h3 style={title}>Manual access policy</h3><p>Manual grants are limited to individual citizen and lawyer plans, require an expiry and reason, are excluded from MRR, and never alter Windcave or another payment provider. Organization plans require an organization-scoped workflow.</p></section></div>
  <section className={styles.card}><div style={heading}><div><p className={styles.eyebrow}>ACCOUNT MEMBERSHIPS</p><h3 style={title}>Subscriptions and access</h3></div><span style={countBadge}>{data?.accounts.total?.toLocaleString()??'—'} accounts</span></div>
   <form onSubmit={search} style={filters}><input aria-label="Search memberships" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name or email" style={input}/><select aria-label="Subscription status" value={status} onChange={event=>changeStatus(event.target.value)} style={select}><option value="">All statuses</option>{['active','trialing','inactive','cancelled','past_due','none'].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Membership plan" value={planCode} onChange={event=>changePlan(event.target.value)} style={select}><option value="">All plans</option>{data?.plans.map(plan=><option key={plan.code} value={plan.code}>{plan.name}</option>)}</select><button className={styles.secondary} disabled={loading}>{loading?'Loading…':'Search'}</button><button type="button" className={styles.secondary} onClick={clearFilters}>Clear</button></form>
   <div style={{overflowX:'auto',marginTop:14}}><table style={table}><thead><tr><th style={th}>Account</th><th style={th}>Access</th><th style={th}>Source</th><th style={th}>Period end</th><th style={th}>Requested</th><th style={th}>Actions</th></tr></thead><tbody>{data?.accounts.items.map(account=><tr key={account.userId}><td style={td}><strong>{account.displayName||'Unnamed account'}</strong><small style={sub}>{account.email}</small><small style={sub}>{account.accountStatus} · {account.identityVerified?'verified':'unverified'}</small></td><td style={td}><strong>{account.planName}</strong><small style={sub}>{account.subscriptionStatus}</small></td><td style={td}><span style={sourceBadge(account.billingProvider)}>{sourceName(account.billingProvider)}</span><small style={sub}>{account.billingInterval||'No billing interval'}</small></td><td style={td}>{account.currentPeriodEnd?new Date(account.currentPeriodEnd).toLocaleDateString():'No fixed end'}</td><td style={td}>{nameFor(account.requestedPlanCode,data?.plans)}</td><td style={td}><div style={actions}><button className={styles.secondary} disabled={busy||account.accountStatus!=='active'||!account.identityVerified} onClick={()=>openGrant(account)}>Grant access</button>{account.billingProvider==='administrator'&&account.subscriptionStatus==='active'&&<button style={danger} disabled={busy} onClick={()=>void revoke(account)}>Revoke grant</button>}</div></td></tr>)}</tbody></table></div>
   {!loading&&data?.accounts.items.length===0&&<div className={styles.empty}>No accounts match these filters.</div>}{(data?.accounts.total??0)>0&&<div style={{...heading,alignItems:'center',marginTop:16}}><span style={sub}>Page {page} of {totalPages}</span><div style={actions}><button className={styles.secondary} disabled={loading||page<=1} onClick={()=>{const next=page-1;setPage(next);void load(next)}}>Previous</button><button className={styles.secondary} disabled={loading||page>=totalPages} onClick={()=>{const next=page+1;setPage(next);void load(next)}}>Next</button></div></div>}</section>
  {grantUser&&<section className={styles.card} style={{borderTop:'3px solid #E5A93C'}}><div style={heading}><div><p className={styles.eyebrow}>TIME-BOUNDED ACCESS</p><h3 style={title}>Grant membership to {grantUser.email}</h3></div><button className={styles.secondary} onClick={()=>setGrantUser(null)}>Close</button></div><form onSubmit={grant} style={grantForm}><label style={label}>Paid plan<select required value={grantPlan} onChange={event=>setGrantPlan(event.target.value)} style={{...select,width:'100%',marginTop:6}}>{data?.plans.filter(isIndividualPaidPlan).map(plan=><option key={plan.code} value={plan.code}>{plan.name}</option>)}</select></label><label style={label}>Access expires<input required type="date" value={expiresAt} min={dateAfter(1)} onChange={event=>setExpiresAt(event.target.value)} style={{...input,width:'100%',marginTop:6}}/></label><label style={{...label,gridColumn:'1 / -1'}}>Reason<textarea required minLength={8} maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Business or service reason" style={textarea}/></label><div style={{...actions,gridColumn:'1 / -1'}}><button style={primary} disabled={busy}>{busy?'Saving…':'Create manual grant'}</button><button type="button" className={styles.secondary} onClick={()=>setGrantUser(null)}>Cancel</button></div></form></section>}
 </div>;
}

function SummaryCard({label,value,note}:{label:string;value?:number|string;note:string}){return <section className={styles.kpi}><span>{label}</span><strong>{value===undefined?'—':typeof value==='number'?value.toLocaleString():value}</strong><small style={sub}>{note}</small></section>}
function isIndividualPaidPlan(plan:Plan){return plan.isPaid&&(plan.audience==='citizen'||plan.audience==='lawyer')}\nfunction nameFor(code:string,plans?:Plan[]){return plans?.find(plan=>plan.code===code)?.name??code.replaceAll('_',' ')}
function sourceName(value?:string|null){return value==='administrator'?'Administrator grant':value||'Internal / free'}
function sourceBadge(value?:string|null){return {display:'inline-block',borderRadius:999,padding:'5px 8px',fontSize:10,fontWeight:900,background:value==='administrator'?'#FFF5D9':value?'#EAF3F8':'#EDF2F5',color:value==='administrator'?'#785918':value?'#315A72':'#405463'}}
function dateAfter(days:number){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}
const summaryGrid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12},heading={display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap' as const},title={fontSize:20,marginTop:5},planGrid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:11,marginTop:16},planCard={border:'1px solid #CBD5DD',borderTop:'3px solid #E5A93C',borderRadius:12,padding:16,background:'#FAFCFD'},audience={fontSize:10,textTransform:'uppercase' as const,letterSpacing:'.08em',fontWeight:900,color:'#667684'},price={display:'block',fontFamily:'Georgia,serif',fontSize:22,color:'#0E2A47'},planStats={display:'flex',justifyContent:'space-between',gap:8,marginTop:16,fontSize:10,color:'#667684'},pricingLink={color:'#0E2A47',fontWeight:900,fontSize:12},demandRow={display:'grid',gridTemplateColumns:'130px 1fr 35px',gap:10,alignItems:'center',fontSize:12},track={height:9,background:'#EDF2F5',borderRadius:999,overflow:'hidden'},fill={height:'100%',background:'#E5A93C',borderRadius:999},filters={display:'flex',gap:8,flexWrap:'wrap' as const,marginTop:16},input={flex:'1 1 250px',border:'1px solid #BFCBD4',borderRadius:9,padding:'10px 12px',fontSize:13,boxSizing:'border-box' as const},select={border:'1px solid #BFCBD4',borderRadius:9,padding:'9px 11px',fontSize:12,background:'#fff',color:'#0E2A47'},countBadge={border:'1px solid #CBD5DD',background:'#F7FAFC',borderRadius:999,padding:'7px 10px',fontSize:11,fontWeight:900,color:'#405463'},table={width:'100%',borderCollapse:'collapse' as const,minWidth:940,fontSize:12},th={textAlign:'left' as const,padding:'10px 8px',borderBottom:'1px solid #CBD5DD',color:'#0E2A47',fontSize:10,textTransform:'uppercase' as const,letterSpacing:'.06em'},td={padding:'12px 8px',borderBottom:'1px solid #E5EAEE',verticalAlign:'top' as const},sub={display:'block',color:'#667684',fontSize:10,marginTop:4,lineHeight:1.4},actions={display:'flex',gap:7,flexWrap:'wrap' as const},danger={border:'1px solid #B9463B',borderRadius:8,padding:'9px 11px',background:'#FFF2F0',color:'#8D2E26',fontWeight:900,cursor:'pointer'},primary={border:'1px solid #C88C24',borderRadius:8,padding:'10px 13px',background:'#E5A93C',color:'#081B2D',fontWeight:900,cursor:'pointer'},grantForm={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14,marginTop:18},label={display:'block',fontSize:12,fontWeight:900,color:'#0E2A47'},textarea={width:'100%',minHeight:90,marginTop:6,border:'1px solid #BFCBD4',borderRadius:9,padding:11,fontFamily:'inherit',boxSizing:'border-box' as const},errorBox={background:'#FFF0EE',border:'1px solid #DCA59F',color:'#862D25',padding:14,borderRadius:10},noticeBox={background:'#EAF6EF',border:'1px solid #AFCFBC',color:'#285F45',padding:14,borderRadius:10};
