'use client';

import { useEffect, useMemo, useState } from 'react';
import { API_BASE, fetchWithTimeout, readApiError, SERVICE_UNAVAILABLE_MESSAGE } from '../../lib/api';
import styles from './dashboard.module.css';

type Dashboard={userId:string;email:string;displayName?:string;planCode:string;subscriptionStatus:string;roles:string[];permissions:string[];dashboardAccess:boolean};
type Member={userId:string;email:string;displayName?:string;emailVerified:boolean;planCode:string;subscriptionStatus:string;roles:string[];permissions:string[]};
type Wallet={balance:number;lifetimePurchased:number;lifetimeGranted:number;lifetimeUsed:number};
type Audience='personal'|'lawyer'|'firm'|'institutional'|'admin';
type NavItem={id:string;label:string;permission?:string};
type AnalyticsSummary={days:number;totals:{pageViews:number;uniqueVisitors:number;signedInUsers:number;guestVisitors:number};daily:{date:string;views:number;visitors:number}[];topPages:{path:string;views:number;visitors:number}[];recent:{path:string;occurredAt:string;device:string;browser:string;referrer?:string|null;email?:string|null;displayName?:string|null;signedIn:boolean}[];devices:{device:string;views:number}[]};

const NAV:Record<Audience,NavItem[]>={
 personal:[{id:'overview',label:'Overview'},{id:'matters',label:'My Legal Matters',permission:'Cases.ViewOwn'},{id:'ai',label:'AI Legal Assistant'},{id:'documents',label:'Documents',permission:'Documents.Analyse'},{id:'referrals',label:'Referrals',permission:'Referrals.Request'},{id:'billing',label:'Billing',permission:'Billing.View'},{id:'account',label:'Account'}],
 lawyer:[{id:'overview',label:'Overview'},{id:'enquiries',label:'Client Enquiries',permission:'Leads.View'},{id:'referrals',label:'Referrals',permission:'Referrals.Manage'},{id:'matters',label:'Matters',permission:'Cases.Manage'},{id:'research',label:'AI Legal Research'},{id:'documents',label:'Document Analysis',permission:'Documents.Analyse'},{id:'profile',label:'My Profile',permission:'LawyerProfile.Manage'},{id:'analytics',label:'Analytics',permission:'Analytics.View'},{id:'billing',label:'Billing',permission:'Billing.View'}],
 firm:[{id:'overview',label:'Overview'},{id:'leads',label:'Lead Pipeline',permission:'Leads.View'},{id:'cases',label:'Cases',permission:'Cases.Manage'},{id:'documents',label:'Documents',permission:'Documents.Analyse'},{id:'referrals',label:'Referrals',permission:'Referrals.Manage'},{id:'firm',label:'Firm Profile',permission:'Firm.Manage'},{id:'team',label:'Team',permission:'FirmUsers.Manage'},{id:'analytics',label:'Analytics',permission:'Analytics.View'},{id:'billing',label:'Billing',permission:'Billing.View'}],
 institutional:[{id:'overview',label:'Overview'},{id:'referrals',label:'Referrals'},{id:'offices',label:'Offices'},{id:'users',label:'Users'},{id:'analytics',label:'Regional Analytics'},{id:'reports',label:'Reports'}],
 admin:[{id:'overview',label:'Platform Overview'},{id:'visitors',label:'Visitor Analytics'},{id:'users',label:'Users'},{id:'memberships',label:'Memberships'},{id:'firms',label:'Law Firms'},{id:'verification',label:'Verification'},{id:'corpus',label:'Legal Corpus'},{id:'aiops',label:'AI Operations'},{id:'analytics',label:'Commercial Analytics',permission:'Analytics.View'},{id:'security',label:'Security & Audit'}]
};

const PLAN_NAME:Record<string,string>={free:'Free',personal_plus:'Personal Plus',lawyer_professional:'Lawyer Professional',firm_starter:'Law Firm Starter',firm_professional:'Law Firm Professional',firm_premium:'Law Firm Premium',institutional:'Institutional'};
function audienceFor(data:Dashboard):Audience{if(data.roles.includes('platform_admin'))return'admin';if(data.roles.includes('institutional')||data.planCode==='institutional')return'institutional';if(data.planCode.startsWith('firm_')||data.roles.some(x=>x==='firm_admin'||x==='firm_staff'))return'firm';if(data.planCode==='lawyer_professional'||data.roles.includes('lawyer'))return'lawyer';return'personal'}
function overviewCopy(a:Audience){return a==='lawyer'?['Lawyer workspace','Manage enquiries, referrals, matters and your professional presence from one workspace.']:a==='firm'?['Law firm workspace','Track legal enquiries, referrals, firm operations and commercial performance.']:a==='institutional'?['Institutional workspace','Coordinate authorised legal-service workflows and monitor access-to-justice demand.']:a==='admin'?['FijiLaw control centre','Manage the platform, memberships, legal corpus, AI operations and commercial performance.']:['My legal workspace','Continue legal matters, organise documents and track referrals in your FijiLaw workspace.']}
function baseKpis(a:Audience){if(a==='lawyer')return[['New enquiries','—'],['Active matters','—'],['Referrals','—']];if(a==='firm')return[['New leads','—'],['Active matters','—'],['Referrals','—']];if(a==='institutional')return[['Open referrals','—'],['Service locations','—'],['Active users','—']];if(a==='admin')return[['Registered users','—'],['Paid members','—'],['MRR','FJD —']];return[['Active matters','—'],['Documents','—'],['Lawyer referrals','—']]}
function moduleCards(a:Audience,planCode:string){const base=a==='personal'?[['My Legal Matters','Saved case workflows and Advanced Legal Triage Reports.'],['Documents & Evidence','Analyse and organise legal documents.'],['Lawyers & Referrals','Track requests for professional legal assistance.'],['Deadlines','Procedural dates and reminders will appear here.']]:a==='lawyer'?[['Client Enquiries','Review incoming enquiries and triage summaries.'],['Referral Review','Accept, decline and manage referred matters.'],['AI Legal Research','Source-grounded Fiji legal research workspace.'],['Professional Profile','Manage practice areas, availability and profile details.']]:a==='firm'?[['Lead Pipeline','Move prospects from enquiry to consultation and matter opening.'],['Firm Matters','Coordinate cases and assigned practitioners.'],['Firm Profile','Manage listing, practice areas and visibility.'],['Team & Offices','Manage practitioners, staff and office locations.']]:a==='institutional'?[['Referral Queue','Authorised referral and service workflows.'],['Offices & Users','Partner locations and access management.'],['Regional Demand','Aggregated legal demand and access trends.'],['Reports','Privacy-preserving institutional reporting.']]:[['Memberships','Paid members, plans, conversions and churn.'],['Visitor Analytics','Track page traffic, guest visitors and signed-in users.'],['Legal Corpus','Verified Fiji legal sources and ingestion status.'],['AI Operations','Model usage, retrieval quality and safety signals.'],['Security & Audit','Administrative actions, access and system controls.']];return base.map(([title,description])=>({title,description,status:title==='Team & Offices'&&planCode==='firm_starter'?'Upgrade required':title==='Visitor Analytics'?'Live module':'Planned module'}))}

function VisitorAnalytics({summary,loading,error,onRange}:{summary:AnalyticsSummary|null;loading:boolean;error:string;onRange:(days:number)=>void}){
 if(loading)return <section className={styles.card}><h3>Visitor Analytics</h3><p>Loading live traffic data…</p></section>;
 if(error)return <section className={styles.card}><h3>Visitor Analytics</h3><p>{error}</p></section>;
 if(!summary)return <section className={styles.card}><h3>Visitor Analytics</h3><p>No analytics data is available yet.</p></section>;
 const maxViews=Math.max(1,...summary.daily.map(x=>x.views));
 return <div className={styles.stack} style={{gap:18}}>
  <section className={styles.card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><p className={styles.eyebrow}>PRIVACY-CONSCIOUS TRAFFIC ANALYTICS</p><h3 style={{marginTop:4}}>Visitors and users</h3></div><div style={{display:'flex',gap:8}}>{[7,30,90].map(days=><button key={days} className={styles.secondary} onClick={()=>onRange(days)}>{days} days</button>)}</div></div><div className={styles.kpis} style={{marginTop:18}}><div className={styles.kpi}><span>Page views</span><strong>{summary.totals.pageViews.toLocaleString()}</strong></div><div className={styles.kpi}><span>Unique visitors</span><strong>{summary.totals.uniqueVisitors.toLocaleString()}</strong></div><div className={styles.kpi}><span>Signed-in users</span><strong>{summary.totals.signedInUsers.toLocaleString()}</strong></div><div className={styles.kpi}><span>Guest visitors</span><strong>{summary.totals.guestVisitors.toLocaleString()}</strong></div></div></section>
  <section className={styles.card}><h3>Traffic by day</h3><div style={{display:'grid',gap:8}}>{summary.daily.slice(-30).map(row=><div key={row.date} style={{display:'grid',gridTemplateColumns:'90px 1fr 90px',gap:10,alignItems:'center',fontSize:13}}><span>{row.date.slice(5)}</span><div style={{height:10,background:'#EDF2F5',borderRadius:999,overflow:'hidden'}}><div style={{width:`${Math.max(3,(row.views/maxViews)*100)}%`,height:'100%',background:'#E5A93C'}}/></div><span>{row.views} views</span></div>)}</div></section>
  <div className={styles.grid}><section className={styles.card}><h3>Top pages</h3><div style={{display:'grid',gap:10}}>{summary.topPages.map(row=><div className={styles.activity} key={row.path}><span>{row.path}</span><small>{row.views} views · {row.visitors} visitors</small></div>)}</div></section><section className={styles.card}><h3>Devices</h3><div style={{display:'grid',gap:10}}>{summary.devices.map(row=><div className={styles.activity} key={row.device}><span style={{textTransform:'capitalize'}}>{row.device}</span><small>{row.views} views</small></div>)}</div><p style={{fontSize:12,color:'#667684',marginTop:18}}>FijiLaw does not store raw visitor IP addresses for this analytics module.</p></section></div>
  <section className={styles.card}><h3>Recent visits</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr><th style={th}>Time</th><th style={th}>Visitor</th><th style={th}>Page</th><th style={th}>Device</th><th style={th}>Source</th></tr></thead><tbody>{summary.recent.map((row,i)=><tr key={`${row.occurredAt}-${i}`}><td style={td}>{new Date(row.occurredAt).toLocaleString()}</td><td style={td}>{row.signedIn?(row.displayName||row.email||'Signed-in user'):'Guest'}</td><td style={td}>{row.path}</td><td style={td}>{row.device} · {row.browser}</td><td style={td}>{row.referrer||'Direct / unknown'}</td></tr>)}</tbody></table></div></section>
 </div>
}
const th={textAlign:'left' as const,padding:'10px 8px',borderBottom:'1px solid #CBD5DD',color:'#0E2A47'};const td={padding:'10px 8px',borderBottom:'1px solid #EDF2F5',verticalAlign:'top' as const};

export default function DashboardPage(){
 const[data,setData]=useState<Dashboard|null>(null);const[member,setMember]=useState<Member|null>(null);const[wallet,setWallet]=useState<Wallet|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[upgrade,setUpgrade]=useState(false);const[unverified,setUnverified]=useState(false);const[section,setSection]=useState('overview');const[visitorAnalytics,setVisitorAnalytics]=useState<AnalyticsSummary|null>(null);const[visitorLoading,setVisitorLoading]=useState(false);const[visitorError,setVisitorError]=useState('');
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(section==='visitors'&&data?.roles.includes('platform_admin'))void loadVisitorAnalytics(30)},[section,data]);
 async function load(){const token=sessionStorage.getItem('fijilaw_access_token');if(!token){window.location.href='/account?mode=login';return}try{const headers={Authorization:`Bearer ${token}`};const meResponse=await fetchWithTimeout(`${API_BASE}/api/membership/me`,{headers,cache:'no-store'},12000);if(meResponse.status===401){sessionStorage.removeItem('fijilaw_access_token');window.location.href='/account?mode=login';return}if(!meResponse.ok)throw new Error(await readApiError(meResponse,'Member profile could not be loaded.'));const meBody=await meResponse.json();setMember(meBody);const response=await fetchWithTimeout(`${API_BASE}/api/dashboard`,{headers,cache:'no-store'},12000);if(response.status===403){const body=await response.json().catch(()=>({}));setUnverified(meBody.emailVerified===false&&meBody.planCode!=='free');setUpgrade(meBody.planCode==='free'||!meBody.permissions?.includes('Dashboard.Access'));setError(body.error??'Your dashboard is currently locked.');return}if(!response.ok)throw new Error(await readApiError(response,'Dashboard could not be loaded.'));setData(await response.json());const creditResponse=await fetchWithTimeout(`${API_BASE}/api/credits/wallet`,{headers,cache:'no-store'},12000);if(creditResponse.ok){const creditBody=await creditResponse.json();setWallet(creditBody.wallet)}}catch(e){setError(e instanceof Error?e.message:SERVICE_UNAVAILABLE_MESSAGE)}finally{setLoading(false)}}
 async function loadVisitorAnalytics(days:number){const token=sessionStorage.getItem('fijilaw_access_token');if(!token)return;setVisitorLoading(true);setVisitorError('');try{const response=await fetchWithTimeout(`${API_BASE}/api/admin/analytics/visitors?days=${days}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'},12000);if(!response.ok)throw new Error(await readApiError(response,'Visitor analytics could not be loaded.'));setVisitorAnalytics(await response.json())}catch(e){setVisitorError(e instanceof Error?e.message:'Visitor analytics could not be loaded.')}finally{setVisitorLoading(false)}}
 async function requestVerification(){const token=sessionStorage.getItem('fijilaw_access_token');if(!token)return;try{const response=await fetchWithTimeout(`${API_BASE}/api/auth/request-email-verification`,{method:'POST',headers:{Authorization:`Bearer ${token}`}},12000);if(!response.ok)throw new Error(await readApiError(response,'Verification request could not be created.'));const body=await response.json().catch(()=>({}));setError(body.deliveryConfigured===false?'Verification was prepared, but outbound email delivery is not enabled yet.':body.message??'Verification request created.')}catch(e){setError(e instanceof Error?e.message:'Verification request could not be created.')}}
 async function logout(){const token=sessionStorage.getItem('fijilaw_access_token');if(token)await fetchWithTimeout(`${API_BASE}/api/auth/logout`,{method:'POST',headers:{Authorization:`Bearer ${token}`}},8000).catch(()=>{});sessionStorage.clear();window.location.href='/'}
 const audience=useMemo(()=>data?audienceFor(data):'personal',[data]);const nav=useMemo(()=>data?NAV[audience].filter(x=>!x.permission||data.permissions.includes(x.permission)):[],[data,audience]);
 if(loading)return <main className={styles.lockedShell}><h1>Loading dashboard…</h1></main>;
 if(unverified)return <main className={styles.lockedShell}><a href="/" className={styles.lockedBrand}>FijiLaw AI</a><p className={styles.eyebrow}>EMAIL VERIFICATION REQUIRED</p><h1 className={styles.lockedTitle}>Verify your email to unlock paid dashboard access.</h1><p className={styles.lockedLead}>{error}</p><div className={styles.lockedCard}><h2>Why this is required</h2><p>Paid legal workflows can contain sensitive information.</p><button onClick={()=>void requestVerification()} className={styles.secondary}>Request verification email</button></div></main>;
 if(upgrade)return <main className={styles.lockedShell}><a href="/" className={styles.lockedBrand}>FijiLaw AI</a><p className={styles.eyebrow}>PAID MEMBER DASHBOARD</p><h1 className={styles.lockedTitle}>Unlock your FijiLaw Dashboard.</h1><p className={styles.lockedLead}>{error}</p><div className={styles.previewGrid}><div className={styles.preview}><strong>My Legal Matters</strong><span>Save and continue cases.</span></div><div className={styles.preview}><strong>Documents</strong><span>Analyse and organise evidence.</span></div><div className={styles.preview}><strong>Referrals</strong><span>Track legal assistance requests.</span></div></div><a href="/pricing" className={styles.cta}>Compare membership plans</a><p><a href="/credits">View FijiLaw AI credit pricing →</a></p></main>;
 if(error||!data)return <main className={styles.lockedShell}><a href="/" className={styles.lockedBrand}>FijiLaw AI</a><h1 className={styles.lockedTitle}>Dashboard unavailable.</h1><p className={styles.lockedLead}>{error}</p><button onClick={()=>{setLoading(true);setError('');void load()}} className={styles.secondary}>Retry</button></main>;
 const[heroTitle,heroText]=overviewCopy(audience);const cards=moduleCards(audience,data.planCode);const kpis=[['FijiLaw Credits',wallet?wallet.balance.toLocaleString():'—'],...baseKpis(audience)];
 const sectionContent=section==='overview'?<><section className={styles.hero}><div><p className={styles.eyebrow}>FIJILAW AI WORKSPACE</p><h2>{heroTitle}</h2><p>{heroText}</p></div><span className={styles.heroTag}>{data.subscriptionStatus} · {PLAN_NAME[data.planCode]??data.planCode}</span></section><div className={styles.kpis}>{kpis.map(([label,value])=><div className={styles.kpi} key={label}><span>{label}</span><strong>{value}</strong>{label==='FijiLaw Credits'&&<a href="/credits" style={{fontSize:12,color:'#0E2A47'}}>Buy / manage credits →</a>}</div>)}</div><div className={styles.grid}><div className={styles.card}><h3>Workspace modules</h3><p>Modules are shown from your role and server-issued permissions.</p><div className={styles.moduleGrid}>{cards.map(card=><article className={styles.module} key={card.title}><h3>{card.title}</h3><p>{card.description}</p><span className={styles.status}>{card.status}</span></article>)}</div></div><div className={styles.stack}><div className={styles.card}><h3>AI credit activity</h3><div className={styles.activity}><span>Available balance</span><small>{wallet?.balance??'—'} credits</small></div><div className={styles.activity}><span>Lifetime used</span><small>{wallet?.lifetimeUsed??'—'}</small></div><div className={styles.activity}><span>Included / granted</span><small>{wallet?.lifetimeGranted??'—'}</small></div><div className={styles.activity}><span>Purchased</span><small>{wallet?.lifetimePurchased??'—'}</small></div><div className={styles.quickActions}><a href="/credits">Open credit wallet</a><a href="/">Use FijiLaw AI</a></div></div><div className={styles.card}><h3>Effective access</h3><div className={styles.permissions}>{data.permissions.map(x=><span key={x}>{x}</span>)}</div></div></div></div></>:section==='visitors'&&audience==='admin'?<VisitorAnalytics summary={visitorAnalytics} loading={visitorLoading} error={visitorError} onRange={days=>void loadVisitorAnalytics(days)}/>:<section className={styles.card}><h3>{nav.find(x=>x.id===section)?.label}</h3><p>This module shell is wired to your access profile. Persistent case, lead and analytics data is being implemented according to the dashboard workplan.</p><div className={styles.empty}>No live records yet.</div><div className={styles.quickActions}><a href="/">Open legal triage</a><a href="/credits">AI credit wallet</a>{data.permissions.includes('Billing.View')&&<a href="/pricing">View plan</a>}</div></section>;
 return <main className={styles.page}><div className={styles.shell}><aside className={styles.sidebar}><a className={styles.brand} href="/">FijiLaw AI</a><div className={styles.identity}><strong>{data.displayName||data.email}</strong><span>{data.email}</span><span className={styles.planBadge}>{PLAN_NAME[data.planCode]??data.planCode}</span></div><nav className={styles.nav}>{nav.map(item=><button key={item.id} className={section===item.id?styles.active:''} onClick={()=>setSection(item.id)}>{item.label}</button>)}</nav><div className={styles.sideFooter}><a className={styles.sideLink} href="/credits">FijiLaw Credits · {wallet?.balance??'—'}</a><a className={styles.sideLink} href="/pricing">Plans & pricing</a><button className={styles.signOut} onClick={()=>void logout()}>Sign out</button></div></aside><section className={styles.content}><header className={styles.topbar}><div><p className={styles.eyebrow}>{audience.toUpperCase()} DASHBOARD</p><h1>{nav.find(x=>x.id===section)?.label??'Overview'}</h1></div><div className={styles.topActions}><a href="/credits">AI Credits: {wallet?.balance??'—'}</a><a href="/">Public site</a><a href="/pricing">Membership</a></div></header>{sectionContent}</section></div></main>;
}
