'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';

type AuthorityRow={category:string;authorityReference:string;relevance:string;sourceUrl?:string;verified:boolean};
type Vulnerability={causeOfAction:string;legalThreshold:string;factApplied:string;riskRating:string};
type AdvancedReport={reportTitle:string;caseReference:string;priority:string;jurisdiction:string;primaryArea:string;secondaryAreas:string[];doctrinalTags:string[];authorities:AuthorityRow[];vulnerabilityMatrix:Vulnerability[];proceduralRoadmap:{decisionDate?:string;awarenessDate?:string;limitationStatus:string;verifiedRule?:string;steps:string[]};evidenceGaps:{criticalMissingDocuments:string[];factsRequiringVerification:string[]};immediateActions:string[];humanLawyerEscalation:string;verification:{retrievalConfidence:string;verifiedAuthorityCount:number;authoritiesRequiringVerification:string[];generatedAtUtc:string};disclaimer:string};
type Result={issue:string;missingInformation:string[];authorities:{title:string;provision?:string;sourceUrl?:string}[];guidance:string;nextSteps:string[];riskLevel:string|number;humanReviewRequired:boolean;disclaimer:string;correlationId:string;advancedReport?:AdvancedReport};
type DocumentResult={fileName:string;characterCount:number;preview:string;assessment:Result;creditsUsed?:number};
type LegalService={id:string;name:string;type:string;city:string;address:string;practiceAreas:string[];verified:boolean};
type ApiStatus='checking'|'online'|'offline';

const API_BASE=(process.env.NEXT_PUBLIC_API_URL??'https://fijilaw-api-production-production.up.railway.app').replace(/\/$/,'');
const legalAreas=[['Public & Administrative Law','Judicial review, public decisions, governance'],['Constitutional Law','Constitutional rights and public power'],['Employment','Dismissal, wages, workplace rights'],['Consumer Rights','Refunds, faulty goods, misleading conduct'],['Family Law','Maintenance, parenting, marriage'],['Land & iTaukei Land','Leases, landowners, customary land'],['Criminal Procedure','Arrest, bail, charges, court process'],['Domestic Violence','Protection and restraining orders']];
function riskLabel(v:string|number){if(typeof v==='number')return v<=0?'Low':v===1?'Medium':'High';return v==='0'?'Low':v;}
function List({items,empty='None identified.'}:{items:string[];empty?:string}){return items?.length?<ul>{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p>{empty}</p>}
function authHeaders(json=true){const token=typeof window!=='undefined'?sessionStorage.getItem('fijilaw_access_token'):null;return {...(json?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})};}
async function apiError(response:Response,fallback:string){const body=await response.json().catch(()=>({}));if(response.status===401)return 'Sign in to use FijiLaw AI. AI services use FijiLaw Credits.';if(response.status===402)return `${body.error??'More FijiLaw Credits are required.'} Balance: ${body.balance??0}. Required: ${body.creditsRequired??'—'}.`;return body.error??body.detail??fallback;}

function AdvancedAssessment({result}:{result:Result}){const r=result.advancedReport;if(!r)return <section className="result"><div className="resultHead"><div><p className="eyebrow">LEGAL TRIAGE</p><h2>{result.issue}</h2></div><span className="risk">{riskLabel(result.riskLevel)} risk</span></div><h3>Guidance</h3><p>{result.guidance}</p><h3>Information still needed</h3><List items={result.missingInformation}/><h3>Next steps</h3><ol>{result.nextSteps.map(x=><li key={x}>{x}</li>)}</ol><p className="disclaimer">{result.disclaimer}</p></section>;
return <section className="result advancedReport"><div className="reportTitle"><p className="eyebrow">FIJILAW AI</p><h2>{r.reportTitle.replace('FijiLaw AI — ','')}</h2><p><strong>Case Reference:</strong> {r.caseReference} &nbsp;|&nbsp; <strong>Priority:</strong> {r.priority} &nbsp;|&nbsp; <strong>Jurisdiction:</strong> {r.jurisdiction}</p></div>{result.humanReviewRequired&&<div className="warning"><strong>Human legal review recommended.</strong></div>}<h3>1. Matter Metadata & Classification Taxonomy</h3><p><strong>Primary Area:</strong> {r.primaryArea}</p><p><strong>Secondary Areas:</strong> {r.secondaryAreas.join(', ')||'None detected'}</p><div className="practicePills">{r.doctrinalTags.map(x=><span key={x}>{x}</span>)}</div><h3>2. Verified Authorities</h3>{r.authorities.length?<div className="tableWrap"><table><thead><tr><th>Category</th><th>Authority</th><th>Relevance</th></tr></thead><tbody>{r.authorities.map((a,i)=><tr key={i}><td>{a.category}</td><td>{a.authorityReference}{a.sourceUrl&&<><br/><a href={a.sourceUrl} target="_blank" rel="noreferrer">Official source ↗</a></>}</td><td>{a.relevance}</td></tr>)}</tbody></table></div>:<p>No verified authorities were retrieved; FijiLaw AI did not invent citations.</p>}<h3>3. Vulnerability Matrix</h3><div className="tableWrap"><table><thead><tr><th>Cause / Issue</th><th>Threshold</th><th>Fact Applied</th><th>Risk</th></tr></thead><tbody>{r.vulnerabilityMatrix.map((v,i)=><tr key={i}><td>{v.causeOfAction}</td><td>{v.legalThreshold}</td><td>{v.factApplied}</td><td>{v.riskRating}</td></tr>)}</tbody></table></div><h3>4. Procedural Roadmap</h3><div className="roadmap"><p><strong>Decision date:</strong> {r.proceduralRoadmap.decisionDate||'Not established'}</p><p><strong>Awareness date:</strong> {r.proceduralRoadmap.awarenessDate||'Not established'}</p><p><strong>Verified rule:</strong> {r.proceduralRoadmap.verifiedRule||'Not retrieved'}</p><p>{r.proceduralRoadmap.limitationStatus}</p></div><h3>5. Evidence & Information Gaps</h3><List items={r.evidenceGaps.factsRequiringVerification}/><h3>6. Recommended Immediate Actions</h3><ol>{r.immediateActions.map((x,i)=><li key={i}>{x}</li>)}</ol><h3>7. Human Lawyer Escalation</h3><p>{r.humanLawyerEscalation}</p><h3>8. Verification & Confidence</h3><p>{r.verification.retrievalConfidence}</p><p className="disclaimer">{r.disclaimer}<br/>Generated: {new Date(r.verification.generatedAtUtc).toLocaleString()}</p></section>}

export default function Home(){
 const[apiStatus,setApiStatus]=useState<ApiStatus>('checking');const[situation,setSituation]=useState('');const[result,setResult]=useState<Result|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[file,setFile]=useState<File|null>(null);const[documentResult,setDocumentResult]=useState<DocumentResult|null>(null);const[documentError,setDocumentError]=useState('');const[documentLoading,setDocumentLoading]=useState(false);const[services,setServices]=useState<LegalService[]>([]);const[cities,setCities]=useState<string[]>([]);const[city,setCity]=useState('');const[query,setQuery]=useState('');
 useEffect(()=>{void initialise()},[]);
 async function initialise(){try{const health=await fetch(`${API_BASE}/health`,{cache:'no-store'});setApiStatus(health.ok?'online':'offline');const response=await fetch(`${API_BASE}/api/legal-services`,{cache:'no-store'});if(response.ok){const body=await response.json();setServices(body.items??[]);setCities(body.cities??[])}}catch{setApiStatus('offline')}}
 const visible=useMemo(()=>services.filter(x=>(!city||x.city===city)&&(!query||`${x.name} ${x.address} ${x.practiceAreas.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[services,city,query]);
 async function submit(e:FormEvent){e.preventDefault();if(!sessionStorage.getItem('fijilaw_access_token')){setError('Sign in first to use FijiLaw AI. Advanced Legal Triage costs 10 FijiLaw Credits.');return;}setLoading(true);setError('');setResult(null);try{const response=await fetch(`${API_BASE}/api/legal/triage`,{method:'POST',headers:authHeaders(),body:JSON.stringify({situation,language:'en'})});if(!response.ok)throw new Error(await apiError(response,'Legal triage could not be completed.'));setResult(await response.json());setApiStatus('online')}catch(e){setError(e instanceof Error?e.message:'Legal triage could not be completed.')}finally{setLoading(false)}}
 function chooseDocument(e:ChangeEvent<HTMLInputElement>){setFile(e.target.files?.[0]??null);setDocumentResult(null);setDocumentError('')}
 async function analyseDocument(e:FormEvent){e.preventDefault();if(!file)return;if(!sessionStorage.getItem('fijilaw_access_token')){setDocumentError('Sign in first to analyse a document. Document analysis costs 15 FijiLaw Credits.');return;}setDocumentLoading(true);setDocumentError('');try{const form=new FormData();form.append('file',file);const response=await fetch(`${API_BASE}/api/legal/documents/analyse`,{method:'POST',headers:authHeaders(false),body:form});if(!response.ok)throw new Error(await apiError(response,'Document analysis could not be completed.'));setDocumentResult(await response.json())}catch(e){setDocumentError(e instanceof Error?e.message:'Document analysis could not be completed.')}finally{setDocumentLoading(false)}}
 return <main className="siteShell"><header className="siteHeader"><a className="brand" href="#top">FijiLaw AI</a><nav className="navLinks"><a href="#services">Get help</a><a href="#legal-directory">Find legal help</a><a href="/pricing">Pricing</a><a href="/credits">AI Credits</a></nav><div className="headerRight"><span className={`serviceStatus ${apiStatus}`}>{apiStatus==='online'?'Service online':apiStatus==='offline'?'Service unavailable':'Checking service'}</span><a className="headerCta" href="/account?mode=login">Sign in</a></div></header>
 <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">ACCESS TO JUSTICE · FIJI</p><h1>Understand your rights. Know your next step.</h1><p className="lead">Advanced Fiji legal triage with verified authority retrieval, procedural issue spotting and human-review escalation.</p><div className="heroActions"><a className="primaryCta" href="#triage">Start legal triage</a><a className="secondaryCta" href="/credits">View AI credit costs</a></div><div className="trustStrip"><span>Verified Fiji-law sources</span><span>No invented citations or deadlines</span><span>Credits refunded if a workflow fails</span></div></div><aside className="heroCard"><span className="cardKicker">FIJILAW CREDITS</span><h2>Pay for AI usage, not access to your API key.</h2><p>Advanced Legal Triage costs 10 FijiLaw Credits. Document analysis costs 15. Plans include credits and members can top up when needed.</p></aside></section>
 <section className="serviceSection" id="services"><div className="sectionHeading"><div><p className="eyebrow">HOW CAN WE HELP?</p><h2>Choose how to start.</h2></div></div><div className="serviceGrid"><a className="serviceCard featuredService" href="#triage"><span className="serviceNumber">01</span><div><h3>Advanced Legal Triage</h3><p>Describe your situation and receive a structured report.</p></div><span className="serviceAction">10 credits →</span></a><a className="serviceCard" href="#document-upload"><span className="serviceNumber">02</span><div><h3>Document Analysis</h3><p>Analyse a PDF, DOCX or TXT legal document.</p></div><span className="serviceAction">15 credits →</span></a><a className="serviceCard" href="#legal-directory"><span className="serviceNumber">03</span><div><h3>Find Legal Help</h3><p>Search lawyers, Legal Aid and legal offices.</p></div><span className="serviceAction">No AI credits →</span></a></div></section>
 <section className="triageSection" id="triage"><div className="triageIntro"><p className="eyebrow">ADVANCED LEGAL TRIAGE · 10 CREDITS</p><h2>Describe what happened.</h2><p>Sign in first. Credits are reserved before the workflow and automatically refunded if it fails.</p><p><a href="/account?mode=login">Sign in</a> · <a href="/credits">Buy / view credits</a></p></div><form className="triageForm" onSubmit={submit}><textarea value={situation} onChange={e=>setSituation(e.target.value)} rows={8} placeholder="Include important dates, documents, decision-makers and the outcome you want." required/><button className="submitButton" disabled={loading||apiStatus==='offline'}>{loading?'Building report…':'Generate report · 10 credits'}</button>{error&&<div className="error"><strong>{error}</strong><p><a href="/account?mode=login">Sign in</a> · <a href="/credits">Get FijiLaw Credits</a></p></div>}</form></section>{result&&<AdvancedAssessment result={result}/>} 
 <section className="documentSection" id="document-upload"><div className="documentIntro"><p className="eyebrow">DOCUMENT ANALYSIS · 15 CREDITS</p><h2>Upload a legal document.</h2><p>PDF, DOCX or TXT. Sensitive documents should only be uploaded when appropriate for the current privacy configuration.</p></div><div className="uploadPanel"><form onSubmit={analyseDocument}><label className="uploadBox" htmlFor="legal-document"><strong>{file?file.name:'Choose a legal document'}</strong><input id="legal-document" type="file" accept=".pdf,.docx,.txt" onChange={chooseDocument}/></label><button className="submitButton" disabled={!file||documentLoading||apiStatus==='offline'}>{documentLoading?'Analysing…':'Analyse document · 15 credits'}</button>{documentError&&<div className="error">{documentError}<p><a href="/account?mode=login">Sign in</a> · <a href="/credits">Get FijiLaw Credits</a></p></div>}</form></div></section>{documentResult&&<><p>Credits used: {documentResult.creditsUsed??15}</p><AdvancedAssessment result={documentResult.assessment}/></>}
 <section className="directorySection" id="legal-directory"><div className="sectionHeading"><div><p className="eyebrow">FIND LEGAL HELP</p><h2>Lawyers, Legal Aid and legal offices.</h2></div></div><div className="directoryFilters"><input aria-label="Search legal services" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search office, address or practice area"/><select value={city} onChange={e=>setCity(e.target.value)}><option value="">All towns & cities</option>{cities.map(x=><option key={x}>{x}</option>)}</select></div><div className="directoryGrid">{visible.map(item=><article className="officeCard" key={item.id}><div className="officeTop"><span className={`verificationBadge ${item.verified?'verified':'pending'}`}>{item.verified?'Verified':'Verification pending'}</span><span>{item.type}</span></div><h3>{item.name}</h3><p>{item.address}</p><div className="practicePills">{item.practiceAreas.slice(0,4).map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section>
 <section className="section" id="legal-help"><div className="sectionHeading"><div><p className="eyebrow">LEGAL AREAS</p><h2>Common areas FijiLaw AI can help you navigate.</h2></div></div><div className="categoryGrid">{legalAreas.map(([title,desc])=><button type="button" className="categoryCard" key={title} onClick={()=>{setSituation(`I need help with ${title}. `);document.getElementById('triage')?.scrollIntoView({behavior:'smooth'})}}><strong>{title}</strong><small>{desc}</small></button>)}</div></section>
 <section className="trustSection"><p className="eyebrow">TRUST, BILLING & SAFETY</p><h2>Credits are charged by FijiLaw—not sold as OpenAI tokens.</h2><p>FijiLaw AI checks your credit wallet server-side before AI-assisted services run. Your OpenAI/API provider credentials are never exposed to users. If a metered workflow fails before completion, the reserved credits are returned automatically.</p></section></main>;
}
