'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';

type AuthorityRow = { category:string; authorityReference:string; relevance:string; sourceUrl?:string; verified:boolean };
type Vulnerability = { causeOfAction:string; legalThreshold:string; factApplied:string; riskRating:string };
type AdvancedReport = {
  reportTitle:string; caseReference:string; priority:string; jurisdiction:string; primaryArea:string; secondaryAreas:string[]; doctrinalTags:string[];
  authorities:AuthorityRow[]; vulnerabilityMatrix:Vulnerability[];
  proceduralRoadmap:{ decisionDate?:string; awarenessDate?:string; limitationStatus:string; verifiedRule?:string; estimatedExpiry?:string; daysRemaining?:number; steps:string[] };
  evidenceGaps:{ factsEstablished:string[]; documentsAvailable:string[]; criticalMissingDocuments:string[]; missingDates:string[]; factsRequiringVerification:string[] };
  immediateActions:string[]; humanLawyerEscalation:string;
  verification:{ retrievalConfidence:string; verifiedAuthorityCount:number; authoritiesRequiringVerification:string[]; conclusionsDependingOnMissingFacts:string[]; generatedAtUtc:string };
  disclaimer:string;
};
type Result = { issue:string; facts:string[]; missingInformation:string[]; authorities:{title:string;provision?:string;sourceUrl?:string}[]; guidance:string; nextSteps:string[]; riskLevel:string|number; humanReviewRequired:boolean; disclaimer:string; correlationId:string; legalDomains?:string[]; advancedReport?:AdvancedReport };
type DocumentResult = { fileName:string; contentType?:string; characterCount:number; preview:string; assessment:Result; note:string };
type LegalService = { id:string; name:string; type:string; city:string; address:string; phone?:string; website?:string; practiceAreas:string[]; verified:boolean; verificationNote:string };
type ApiStatus = 'checking'|'online'|'offline';

const legalAreas = [['Public & Administrative Law','Judicial review, public decisions, governance'],['Constitutional Law','Constitutional rights and public power'],['Employment','Dismissal, wages, workplace rights'],['Consumer Rights','Refunds, faulty goods, misleading conduct'],['Family Law','Maintenance, parenting, marriage'],['Land & iTaukei Land','Leases, landowners, customary land'],['Criminal Procedure','Arrest, bail, charges, court process'],['Domestic Violence','Protection and restraining orders']];
const entryPaths = [['Tell Me My Rights','Describe a situation and receive an advanced legal triage report.','Start assessment','#triage'],['Upload a Legal Document','Understand a letter, contract, notice or other legal document.','Analyse document','#document-upload'],['Find a Lawyer','Search for a legal practitioner by area of law and location.','Search directory','#legal-directory'],['Find Legal Aid','Identify public and community legal assistance options.','Find Legal Aid','#legal-directory'],['Nearest Legal Office','Find an appropriate legal office based on your town or city.','Find office','#legal-directory'],['Continue My Case','Return to a saved matter, evidence timeline and previous assessment.','Account required','#services']];

function riskLabel(value:string|number){ if(typeof value==='number') return value<=0?'Low':value===1?'Medium':'High'; if(value==='0') return 'Low'; return value; }
function friendlyApiError(status:ApiStatus){ return status==='offline'?'FijiLaw AI is temporarily unable to reach the legal service. Your information has not been submitted. Please try again shortly.':'FijiLaw AI could not complete this request. Please try again.'; }

function List({items,empty='None identified.'}:{items:string[];empty?:string}){ return items?.length?<ul>{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p>{empty}</p>; }
function AdvancedAssessment({result,title='Advanced Legal Triage Report'}:{result:Result;title?:string}){
  const r=result.advancedReport;
  if(!r) return <section className="result"><div className="resultHead"><div><p className="eyebrow">{title.toUpperCase()}</p><h2>{result.issue}</h2></div><span className="risk">{riskLabel(result.riskLevel)} risk</span></div><h3>Guidance</h3><p>{result.guidance}</p><h3>Information still needed</h3><List items={result.missingInformation}/><h3>Next steps</h3><ol>{result.nextSteps.map(x=><li key={x}>{x}</li>)}</ol><h3>Verified authorities</h3><List items={result.authorities.map(a=>`${a.title}${a.provision?` — ${a.provision}`:''}`)} empty="No verified authorities retrieved."/><p className="disclaimer">{result.disclaimer}<br/>Reference: {result.correlationId}</p></section>;
  return <section className="result advancedReport">
    <div className="reportTitle"><p className="eyebrow">FIJILAW AI</p><h2>{r.reportTitle.replace('FijiLaw AI — ','')}</h2><p><strong>Case Reference:</strong> {r.caseReference} &nbsp;|&nbsp; <strong>Priority:</strong> {r.priority} &nbsp;|&nbsp; <strong>Jurisdiction:</strong> {r.jurisdiction}</p></div>
    {result.humanReviewRequired&&<div className="warning"><strong>Human legal review recommended.</strong> This matter should not rely on AI alone.</div>}
    <h3>1. Matter Metadata & Classification Taxonomy</h3><p><strong>Primary Area:</strong> {r.primaryArea}</p><p><strong>Secondary Areas:</strong> {r.secondaryAreas.join(', ')||'None detected'}</p><div className="practicePills">{r.doctrinalTags.map(x=><span key={x}>{x}</span>)}</div>
    <h3>2. Automated Retrieval & Statutory Authorities</h3>{r.authorities.length?<div className="tableWrap"><table><thead><tr><th>Category</th><th>Authority Reference</th><th>Relevance / Legal Principle</th></tr></thead><tbody>{r.authorities.map((a,i)=><tr key={`${a.authorityReference}-${i}`}><td>{a.category}</td><td><strong>{a.authorityReference}</strong>{a.sourceUrl&&<><br/><a href={a.sourceUrl} target="_blank" rel="noreferrer">Official source ↗</a></>}</td><td>{a.relevance}</td></tr>)}</tbody></table></div>:<p>No verified legal authorities were retrieved. The system will not invent citations.</p>}
    <h3>3. Deep Legal Analysis & Vulnerability Matrix</h3><div className="tableWrap"><table><thead><tr><th>Cause of Action</th><th>Legal Threshold / Standard</th><th>Fact Applied</th><th>Risk Rating</th></tr></thead><tbody>{r.vulnerabilityMatrix.map((v,i)=><tr key={`${v.causeOfAction}-${i}`}><td>{v.causeOfAction}</td><td>{v.legalThreshold}</td><td>{v.factApplied}</td><td><strong>{v.riskRating}</strong></td></tr>)}</tbody></table></div>
    <h3>4. Procedural Roadmap & Limitation Period Calculator</h3><div className="roadmap"><p><strong>Decision/event date:</strong> {r.proceduralRoadmap.decisionDate||'Not established'}</p><p><strong>Awareness date:</strong> {r.proceduralRoadmap.awarenessDate||'Not established'}</p><p><strong>Verified procedural rule:</strong> {r.proceduralRoadmap.verifiedRule||'Not retrieved'}</p><p><strong>Limitation status:</strong> {r.proceduralRoadmap.limitationStatus}</p>{r.proceduralRoadmap.estimatedExpiry&&<p><strong>Estimated expiry:</strong> {r.proceduralRoadmap.estimatedExpiry}</p>}<div className="timeline">EVENT / DECISION<br/>↓<br/>VERIFY DATES & APPLICABLE RULE<br/>↓<br/>PRESERVE EVIDENCE<br/>↓<br/>QUALIFIED LEGAL REVIEW<br/>↓<br/>POTENTIAL PROCEEDING</div></div>
    <h3>5. Evidence & Information Gap Analysis</h3><p><strong>Critical missing documents</strong></p><List items={r.evidenceGaps.criticalMissingDocuments}/><p><strong>Missing dates / facts requiring verification</strong></p><List items={r.evidenceGaps.factsRequiringVerification}/>
    <h3>6. Recommended Immediate Actions</h3><ol>{r.immediateActions.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ol>
    <h3>7. Human Lawyer Escalation</h3><p>{r.humanLawyerEscalation}</p>
    <h3>8. Verification & Confidence Statement</h3><p><strong>Retrieval confidence:</strong> {r.verification.retrievalConfidence}</p><p><strong>Verified authorities:</strong> {r.verification.verifiedAuthorityCount}</p><List items={r.verification.authoritiesRequiringVerification} empty="No additional authority category specifically flagged by the automated verifier."/><p className="disclaimer">{r.disclaimer}<br/>Reference: {result.correlationId} · Generated: {new Date(r.verification.generatedAtUtc).toLocaleString()}</p>
  </section>;
}

export default function Home(){
 const apiBase=(process.env.NEXT_PUBLIC_API_URL??'https://fijilaw-api-production-production.up.railway.app').replace(/\/$/,'');
 const [apiStatus,setApiStatus]=useState<ApiStatus>('checking'); const [situation,setSituation]=useState(''); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const [documentFile,setDocumentFile]=useState<File|null>(null); const [documentResult,setDocumentResult]=useState<DocumentResult|null>(null); const [documentLoading,setDocumentLoading]=useState(false); const [documentError,setDocumentError]=useState('');
 const [services,setServices]=useState<LegalService[]>([]); const [cities,setCities]=useState<string[]>([]); const [directoryLoading,setDirectoryLoading]=useState(true); const [directoryError,setDirectoryError]=useState(''); const [city,setCity]=useState(''); const [serviceType,setServiceType]=useState(''); const [area,setArea]=useState(''); const [directoryQuery,setDirectoryQuery]=useState('');
 async function checkApi(){setApiStatus('checking');try{const response=await fetch(`${apiBase}/health`,{cache:'no-store'});setApiStatus(response.ok?'online':'offline')}catch{setApiStatus('offline')}}
 async function loadDirectory(){setDirectoryLoading(true);setDirectoryError('');try{const response=await fetch(`${apiBase}/api/legal-services`,{cache:'no-store'});if(!response.ok)throw new Error();const body=await response.json();setServices(body.items??[]);setCities(body.cities??[])}catch{setDirectoryError(friendlyApiError(apiStatus))}finally{setDirectoryLoading(false)}}
 useEffect(()=>{checkApi()},[apiBase]); useEffect(()=>{if(apiStatus!=='checking')loadDirectory()},[apiStatus]);
 const visibleServices=useMemo(()=>services.filter(s=>{const q=directoryQuery.trim().toLowerCase();return(!city||s.city===city)&&(!serviceType||s.type.includes(serviceType))&&(!area||s.practiceAreas.some(x=>x.toLowerCase().includes(area.toLowerCase()))||s.practiceAreas.includes('General'))&&(!q||`${s.name} ${s.address} ${s.city} ${s.practiceAreas.join(' ')}`.toLowerCase().includes(q))}),[services,city,serviceType,area,directoryQuery]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');setResult(null);try{const response=await fetch(`${apiBase}/api/legal/triage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({situation,language:'en'})});if(!response.ok)throw new Error();setResult(await response.json());setApiStatus('online')}catch{setError(friendlyApiError(apiStatus));setApiStatus('offline')}finally{setLoading(false)}}
 function chooseDocument(e:ChangeEvent<HTMLInputElement>){setDocumentError('');setDocumentResult(null);setDocumentFile(e.target.files?.[0]??null)}
 async function analyseDocument(e:FormEvent){e.preventDefault();if(!documentFile)return;setDocumentLoading(true);setDocumentError('');setDocumentResult(null);try{const form=new FormData();form.append('file',documentFile);const response=await fetch(`${apiBase}/api/legal/documents/analyse`,{method:'POST',body:form});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??body.detail??'The document could not be analysed.');setDocumentResult(body);setApiStatus('online')}catch(e){setDocumentError(e instanceof Error&&e.message!=='Failed to fetch'?e.message:friendlyApiError(apiStatus));setApiStatus('offline')}finally{setDocumentLoading(false)}}
 return <main className="siteShell">
 <header className="siteHeader"><a className="brand" href="#top">FijiLaw AI</a><nav className="navLinks"><a href="#services">Get help</a><a href="#legal-directory">Find legal help</a><a href="#legal-help">Legal areas</a><a href="#trust">Trust & safety</a></nav><div className="headerRight"><span className={`serviceStatus ${apiStatus}`}>{apiStatus==='online'?'Service online':apiStatus==='offline'?'Service unavailable':'Checking service'}</span><a className="headerCta" href="#triage">Start assessment</a></div></header>
 {apiStatus==='offline'&&<section className="serviceAlert"><div><strong>FijiLaw AI legal service is temporarily unavailable.</strong><p>Your information has not been submitted.</p></div><button onClick={checkApi}>Retry connection</button></section>}
 <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">ACCESS TO JUSTICE · FIJI</p><h1>Understand your rights. Know your next step.</h1><p className="lead">Advanced Fiji legal triage with multi-domain classification, verified authority retrieval, procedural issue spotting, evidence gaps and human-review escalation.</p><div className="heroActions"><a className="primaryCta" href="#triage">Tell me what happened</a><a className="secondaryCta" href="#legal-directory">Find legal help</a></div><div className="trustStrip"><span>Verified Fiji-law sources</span><span>No invented citations or deadlines</span><span>Human review for high-risk matters</span></div></div><aside className="heroCard"><span className="cardKicker">ADVANCED LEGAL TRIAGE</span><h2>Start with your story.</h2><p>You do not need to know the Act or legal term. FijiLaw AI structures the matter and reports what can—and cannot—be verified.</p></aside></section>
 <section className="serviceSection" id="services"><div className="sectionHeading"><div><p className="eyebrow">HOW CAN WE HELP?</p><h2>Choose the way you want to start.</h2></div></div><div className="serviceGrid">{entryPaths.map(([title,desc,action,href],index)=><a className={`serviceCard ${index===0?'featuredService':''}`} href={href} key={title}><span className="serviceNumber">0{index+1}</span><div><h3>{title}</h3><p>{desc}</p></div><span className="serviceAction">{action} →</span></a>)}</div></section>
 <section className="directorySection" id="legal-directory"><div className="sectionHeading"><div><p className="eyebrow">FIND LEGAL HELP</p><h2>Lawyers, Legal Aid and legal offices.</h2></div></div><div className="directoryFilters"><input aria-label="Search legal services" value={directoryQuery} onChange={e=>setDirectoryQuery(e.target.value)} placeholder="Search office, address or practice area"/><select value={city} onChange={e=>setCity(e.target.value)}><option value="">All towns & cities</option>{cities.map(x=><option key={x}>{x}</option>)}</select><select value={serviceType} onChange={e=>setServiceType(e.target.value)}><option value="">All service types</option><option value="Legal Aid">Legal Aid</option><option value="Private Law Firm">Private law firms</option></select><select value={area} onChange={e=>setArea(e.target.value)}><option value="">All legal areas</option>{legalAreas.map(([x])=><option key={x}>{x}</option>)}</select></div>{directoryLoading&&<p>Loading legal services…</p>}{directoryError&&<p className="error">{directoryError}</p>}<div className="directoryGrid">{visibleServices.map(item=><article className="officeCard" key={item.id}><div className="officeTop"><span className={`verificationBadge ${item.verified?'verified':'pending'}`}>{item.verified?'Verified':'Verification pending'}</span><span>{item.type}</span></div><h3>{item.name}</h3><p>{item.address}</p><div className="practicePills">{item.practiceAreas.slice(0,4).map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section>
 <section className="documentSection" id="document-upload"><div className="documentIntro"><p className="eyebrow">DOCUMENT ANALYSIS</p><h2>Upload a legal document.</h2><p>PDF, DOCX or TXT. Scanned image-only PDFs are not yet supported.</p></div><div className="uploadPanel"><form onSubmit={analyseDocument}><label className="uploadBox" htmlFor="legal-document"><strong>{documentFile?documentFile.name:'Choose a legal document'}</strong><input id="legal-document" type="file" accept=".pdf,.docx,.txt" onChange={chooseDocument}/></label><button className="submitButton" disabled={!documentFile||documentLoading||apiStatus==='offline'}>{documentLoading?'Analysing…':'Analyse document'}</button></form></div></section>{documentError&&<p className="error">{documentError}</p>}{documentResult&&<AdvancedAssessment result={documentResult.assessment} title="Document Advanced Legal Triage Report"/>}
 <section className="section" id="legal-help"><div className="sectionHeading"><div><p className="eyebrow">LEGAL AREAS</p><h2>Common areas FijiLaw AI can help you navigate.</h2></div></div><div className="categoryGrid">{legalAreas.map(([title,desc])=><button type="button" className="categoryCard" key={title} onClick={()=>{setSituation(`I need help with ${title}. `);document.getElementById('triage')?.scrollIntoView({behavior:'smooth'})}}><strong>{title}</strong><small>{desc}</small></button>)}</div></section>
 <section className="triageSection" id="triage"><div className="triageIntro"><p className="eyebrow">ADVANCED LEGAL TRIAGE</p><h2>Describe what happened.</h2><p>Include relevant dates, documents, decision-makers and the outcome you want. Do not include passwords, banking PINs or unnecessary sensitive information.</p></div><form className="triageForm" onSubmit={submit}><textarea value={situation} onChange={e=>setSituation(e.target.value)} rows={8} placeholder="Example: A public body made a decision affecting me on 12/08/2026. I received the written decision on 15/08/2026..." required/><button className="submitButton" disabled={loading||apiStatus==='offline'}>{loading?'Building report…':'Generate Advanced Legal Triage Report'}</button></form></section>
 {error&&<p className="error">{error}</p>}{result&&<AdvancedAssessment result={result}/>} 
 <section className="trustSection" id="trust"><p className="eyebrow">TRUST & SAFETY</p><h2>Verified law first. No invented authorities or deadlines.</h2><p>Where a procedural rule, limitation period, statute or case has not been retrieved and verified, FijiLaw AI reports the gap rather than guessing.</p></section>
 </main>;
}
